### PR TITLE
Fixes logic for custom amount

### PR DESCRIPTION
**Pull request by NejcZdovc**
core implementation: https://github.com/brave/brave-core/pull/910

### CODE REVIEW

**Comment by NejcZdovc** [comment]
will be merged when https://github.com/brave/brave-core/pull/910 will be reviewed

**Comment by jasonrsadler** [comment]
0.57.x: fd1df35
0.58.x: 807e0d9
master: 45c3a7f

**Comment by bbondy** [comment]
This is breaking builds on Windows

```
../../brave/vendor/bat-native-ledger/src/bat_state.cc(119,10):  error: no member named 'sort' in namespace 'std'
    std::sort(properties.parameters_choices_.begin(),
    ~~~~~^
../../brave/vendor/bat-native-ledger/src/bat_state.cc(281,12):  error: no member named 'sort' in namespace 'std'
      std::sort(properties.parameters_choices_.begin(),
      ~~~~~^
2 errors generated.
```

**Comment by bbondy** [comment]
Was there an approval request for this?

**Comment by NejcZdovc** [comment]
@bbondy this is part of import logic so that's why it's in 57

**Pull request merged**
