### PR TITLE
Use IO thread instead of UI thread

### LINKED ISSUE #2: Debug assertion for IO on no-blocking thread
```
[39551:775:0702/104607.259415:ERROR:bat_client.cc(51)] BatClient::loadStateOrRegisterPersona exit
[39551:32515:0702/104607.259491:ERROR:bat_client.cc(56)] !!!here1
[39551:32515:0702/104607.259555:ERROR:bat_client_webrequest_chromium.cc(86)] !!!web_request URL == https://ledger-staging.mercury.basicattentiontoken.org/v2/registrar/persona
[39551:775:0702/104607.259466:FATAL:thread_restrictions.cc(29)] Check failed: !g_blocking_disallowed.Get().Get(). Function marked as blocking was called from a scope that disallows blocking! If this task is running inside the TaskScheduler, it needs to have MayBlock() in its TaskTraits. Otherwise, consider making this blocking work asynchronous or, as a last resort, you may use ScopedAllowBlocking in a narrow scope.
0   libbase.dylib                       0x0000000109fbfb3e base::debug::StackTrace::StackTrace(unsigned long) + 174
1   libbase.dylib                       0x0000000109fbfbfd base::debug::StackTrace::StackTrace(unsigned long) + 29
2   libbase.dylib                       0x0000000109fbe0ac base::debug::StackTrace::StackTrace() + 28
3   libbase.dylib                       0x000000010a05b19c logging::LogMessage::~LogMessage() + 460
4   libbase.dylib                       0x000000010a058f05 logging::LogMessage::~LogMessage() + 21
5   libbase.dylib                       0x000000010a2c88fc base::AssertBlockingAllowed() + 188
6   libbase.dylib                       0x000000010a0071af base::File::Close() + 111
7   libbase.dylib                       0x0000000109fe0cc9 base::File::~File() + 25
8   libbase.dylib                       0x0000000109fe0d15 base::File::~File() + 21
9   libleveldatabase.dylib              0x00000001368b4d21 leveldb_env::(anonymous namespace)::ChromiumFileLock::~ChromiumFileLock() + 65
10  libleveldatabase.dylib              0x00000001368b4ca5 leveldb_env::(anonymous namespace)::ChromiumFileLock::~ChromiumFileLock() + 21
11  libleveldatabase.dylib              0x00000001368b4cc9 leveldb_env::(anonymous namespace)::ChromiumFileLock::~ChromiumFileLock() + 25
12  libleveldatabase.dylib              0x00000001368a599a leveldb_env::ChromiumEnv::UnlockFile(leveldb::FileLock*) + 1258
13  libleveldatabase.dylib              0x00000001368c64da leveldb::DBImpl::~DBImpl() + 202
14  libleveldatabase.dylib              0x00000001368c68a5 leveldb::DBImpl::~DBImpl() + 21
15  libleveldatabase.dylib              0x00000001368c68c9 leveldb::DBImpl::~DBImpl() + 25
16  libchrome_dll.dylib                 0x00000001119b92b3 braveledger_bat_get_media::BatGetMedia::~BatGetMedia() + 67
17  libchrome_dll.dylib                 0x00000001119b9325 braveledger_bat_get_media::BatGetMedia::~BatGetMedia() + 21
18  libchrome_dll.dylib                 0x0000000111983643 braveledger_ledger::Ledger::~Ledger() + 83
19  libchrome_dll.dylib                 0x0000000111983835 braveledger_ledger::Ledger::~Ledger() + 21
20  libchrome_dll.dylib                 0x000000011176d969 BraveBrowserCommandController::ExecuteBraveCommandWithDisposition(int, WindowOpenDisposition) + 921
21  libchrome_dll.dylib                 0x000000011176d5a0 BraveBrowserCommandController::ExecuteCommandWithDisposition(int, WindowOpenDisposition) + 64
22  libchrome_dll.dylib                 0x0000000117e26911 chrome::BrowserCommandController::ExecuteCommand(int) + 33
23  libchrome_dll.dylib                 0x0000000117e2b5ec chrome::ExecuteCommand(Browser*, int) + 44
24  libchrome_dll.dylib                 0x0000000117f6f3c7 AppMenuModel::ExecuteCommand(int, int) + 135
25  libui_base.dylib                    0x000000010a94be7e ui::SimpleMenuModel::ActivatedAt(int, int) + 94
26  libui_base.dylib                    0x000000010a8f800d -[MenuControllerCocoa itemSelected:uiEventFlags:] + 509
27  libui_base.dylib                    0x000000010a8f7afa -[MenuControllerCocoa itemSelected:] + 874
28  AppKit                              0x00007fff29f7d75a -[NSApplication(NSResponder) sendAction:to:from:] + 312
29  libchrome_dll.dylib                 0x00000001125f55a7 __43-[BrowserCrApplication sendAction:to:from:]_block_invoke + 87
30  libbase.dylib                       0x000000010a06065a base::mac::CallWithEHFrame(void () block_pointer) + 10
31  libchrome_dll.dylib                 0x00000001125f542b -[BrowserCrApplication sendAction:to:from:] + 1211
32  AppKit                              0x00007fff29a125f7 -[NSMenuItem _corePerformAction] + 323
33  AppKit                              0x00007fff29a1237f -[NSCarbonMenuImpl performActionWithHighlightingForItemAtIndex:] + 114
34  AppKit                              0x00007fff29a97fba -[NSMenu performActionForItemAtIndex:] + 133
35  AppKit                              0x00007fff29a97f25 -[NSMenu _internalPerformActionForItemAtIndex:] + 94
36  AppKit                              0x00007fff29a97d55 -[NSCarbonMenuImpl _carbonCommandProcessEvent:handlerCallRef:] + 106
37  AppKit                              0x00007fff2995e6b2 NSSLMMenuEventHandler + 882
38  HIToolbox                           0x00007fff2b4f3814 DispatchEventToHandlers(EventTargetRec*, OpaqueEventRef*, HandlerCallRec*) + 1541
39  HIToolbox                           0x00007fff2b4f2b5d SendEventToEventTargetInternal(OpaqueEventRef*, OpaqueEventTargetRef*, HandlerCallRec*) + 374
40  HIToolbox                           0x00007fff2b507e61 SendEventToEventTarget + 39
41  HIToolbox                           0x00007fff2b551489 SendHICommandEvent(unsigned int, HICommand const*, unsigned int, unsigned int, unsigned char, void const*, OpaqueEventTargetRef*, OpaqueEventTargetRef*, OpaqueEventRef**) + 411
42  HIToolbox                           0x00007fff2b57a3be SendMenuCommandWithContextAndModifiers + 49
43  HIToolbox                           0x00007fff2b57a37a SendMenuItemSelectedEvent + 188
44  HIToolbox                           0x00007fff2b57a254 FinishMenuSelection(SelectionData*, MenuResult*, MenuResult*) + 96
45  HIToolbox                           0x00007fff2b692b9c PopUpMenuSelectCore(MenuData*, Point, double, Point, unsigned short, unsigned int, unsigned int, Rect const*, unsigned short, unsigned int, Rect const*, Rect const*, __CFDictionary const*, __CFString const*, OpaqueMenuRef**, unsigned short*) + 1662
46  HIToolbox                           0x00007fff2b692017 _HandlePopUpMenuSelection8(OpaqueMenuRef*, OpaqueEventRef*, unsigned int, Point, unsigned short, unsigned int, unsigned int, Rect const*, unsigned short, Rect const*, Rect const*, __CFDictionary const*, __CFString const*, OpaqueMenuRef**, unsigned short*) + 409
47  HIToolbox                           0x00007fff2b55a4bc _HandlePopUpMenuSelectionWithDictionary + 268
48  AppKit                              0x00007fff29a8eada _NSSLMPopUpCarbonMenu3 + 5632
49  AppKit                              0x00007fff29a8d434 -[NSCarbonMenuImpl popUpMenu:atLocation:width:forView:withSelectedItem:withFont:withFlags:withOptions:] + 439
50  AppKit                              0x00007fff29afd59c -[NSPopUpButtonCell trackMouse:inRect:ofView:untilMouseUp:] + 570
51  AppKit                              0x00007fff29b763a7 -[NSPopUpButtonCell performClickWithFrame:inView:] + 128
52  libchrome_dll.dylib                 0x000000011840fc8d -[MenuButton(Private) showMenu:] + 1549
53  libchrome_dll.dylib                 0x0000000118410077 -[MenuButton(Private) dragShowMenu:] + 279
54  AppKit                              0x00007fff29f7d75a -[NSApplication(NSResponder) sendAction:to:from:] + 312
55  libchrome_dll.dylib                 0x00000001125f55a7 __43-[BrowserCrApplication sendAction:to:from:]_block_invoke + 87
56  libbase.dylib                       0x000000010a06065a base::mac::CallWithEHFrame(void () block_pointer) + 10
57  libchrome_dll.dylib                 0x00000001125f542b -[BrowserCrApplication sendAction:to:from:] + 1211
58  AppKit                              0x00007fff29a23933 -[NSControl sendAction:to:] + 86
59  libchrome_dll.dylib                 0x0000000118336b0d -[ClickHoldButtonCell trackMouse:inRect:ofView:untilMouseUp:] + 2013
60  AppKit                              0x00007fff29a20a64 -[NSControl mouseDown:] + 965
61  AppKit                              0x00007fff2a11c959 -[NSWindow(NSEventRouting) _handleMouseDownEvent:isDelayedEvent:] + 5891
```

### PR DESCRIPTION
**Pull request by gdregalo**
Fix #2

### CODE REVIEW

**Comment by bbondy** [comment]
Turns out this one is not the right fix and also it introduces a different issue before the original fix.  The PostTask shouldn't be needed here at all.

**Comment by bbondy** [comment]
Turns out this one is not the right fix and also it introduces a different issue before the original fix. The PostTask shouldn't be needed here at all.

**Comment by bbondy** [comment]
Since it's a different issue, you can remove the Fix #2 from the message. I'd accept something that removes the PostTask, but it wouldn't fix #2 though.

**Comment by bridiver** [comment]
I think this is no longer necessary

**Pull request closed without merging**
